### ISSUE TITLE
Getting Null response when using meetup api

### ISSUE THREAD

**Issue by nidhinkumar06** [actions-on-google/dialogflow-gdg-nodejs#2]
I have tried using meetup api but i am getting the following response in console.

`meetup is Meetup {
  abort: [Function],
  timeout: [Function],
  on: [Function],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners],
  setMaxListeners: [Function: setMaxListeners] }`

and the error code as

`Error: getaddrinfo EAI_AGAIN api.meetup.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)`

GetEvents:

`meetup.getGroup({
                urlname: this.gdgId,
            }, (err, resp) => {
              console.log('resp is', resp);
               if (err) {
                    reject(err);
                } else {
                    this.info = resp;
                    resolve(resp);
                }
            });
`
I have tried the same in postman there i am getting the response

**Comment by YTolun** [comment]
Hey there, are you using the Free Plan of the Firebase Cloud Functions?

If so, you're having this error because Firebase doesn't allow calling non-google APIs on their free plan. Upgrade to Blaze to see if that makes any difference. (BEWARE: Blaze is a paid plan and if certain limits were to be exceeded, you will be charged.)

Otherwise, you may want to use another server for your fulfillment.

**Comment by dzuluaga** [comment]
Yeah. That's likely due to Firebase Spark plan, which limits external API calls.

You can run the same API in [Google App Engine Standard](https://cloud.google.com/appengine/docs/standard/nodejs/building-app/writing-web-service), which shouldn't require enabling billing. I can't confirm Node.js, but worth a try. Please us know how it goes.

**Comment by dzuluaga** [comment]
> Yeah. That's likely due to Firebase Spark plan, which limits external API calls.
> 
> You can run the same API in [Google App Engine Standard](https://cloud.google.com/appengine/docs/standard/nodejs/building-app/writing-web-service), which shouldn't require enabling billing. I can't confirm Node.js, but worth a try. Please us know how it goes.

I've just tested GAE Standard Node.js, and it requires billing.
